src/game.go
Fixed the bug that caused any games that go above a total duration of 30 minutes and 1 second to be instantly killed.
=> Fixed table timeout bug

public/js/constants.js, public/js/ui.js, src/character.go
- Replaced the ugly red circle that was being used to represent a player's character, with an emoji unique to that character, so that people can tell what the character is without needing to mouse over it;
- made a method for ending the turn to reduce code;
=> Use emojis instead of red circles as the character indicator

src/character.go
vulnerable and color-blind were not checked if the giving player was one of the characters above.
I did not compile or test this change.
=> remove superfluous `else`

docs/VARIANTS.md, public/js/src/constants.js, public/js/src/game/HanabiCard.js, public/js/src/game/drawCards.js, public/js/src/game/ui/HanabiCard.js, public/js/src/game/ui/drawCards.js, src/variantDefinitions.go, src/variants.go
New suit: Gray, touched by no colours and critical
New variants: Gray (5 suits), Gray (6 suits), Black and Gray (6 suits), Gray and Rainbow (6 Suits), Gray and Dark Rainbow (6 Suits).
Proposed Triple Black variant (Grey, Black, and Dark Rainbow (6 suits)) scrapped.
Gray, the suit for rank clued cards of unknown colour, changed to Gray_Unknown.
=> Gray suit and variants

docs/FEATURES.md, public/js/src/game/ui/HanabiCard.js, public/js/src/game/ui/HanabiCardClick.js
Alt + middle-click still goes to first turn it was clued. 
This also works in the replay, allowing you to middle-click a card several times to go backwards through each time it was clued.
=> Middle-clicking card goes to last turn it was clued

src/httpScores.go, src/httpStats.go, src/views/missingScores.tmpl, src/views/scores.tmpl, src/views/stats.tmpl
The code has four conflictingly named variables when keeping track of max scores. But ultimately what we need is two: one to track total max scores (`NumMaxScores`), and one to track and array of max scores for each person size variant (`NumMaxScoresPerType`).  Getting rid of the conflictingly named variables makes the template variable usage more clear.
Closes #807.
=> Fixed max scores global stats

.dockerignore, .travis.yml, docker/.env_template, docker/Dockerfile, docker/docker-compose.yml, docker/src/go.mod, docker/src/go.sum, docker/src/main.go, docs/INSTALL.md
The existing Dockerfile is made for a development environment. In particular to run the docker-compose.yml file it is required to manually compile the frontend dependencies on the host machine. Furthermore it runs the hanabi-live daemon as root inside the docker container, which
is a security issue.
This PR adds a Dockerfile and docker-compose.yml for a production setup in the 'docker' folder. This does not have any dependencies on the host environment and can be built on a server having only a checkout of this repository and the docker-compose executable. The Dockerfile uses a common docker practice of "multi-stage builds" to achieve this. It also mitigates most security risks by running hanabi-live as a limited user within Docker.
A new section on how to start this docker image has been …
=> Add a docker configuration for production

public/js/src/game/ui/HanabiCard.ts
Should fix current outstanding empathy issues. Negative color clues now
give negative rainbow even in special-ones/fives. Rank clues can now
result in crossed-out suit pips even in pink variants.
=> Fix empathy in special suits

public/js/src/game/ui/action.ts
Fixes #1105. identityDetermined is supposed to be if the holder of the card knows its identity, not everyone else.
=> Fix identityDetermined

client/src/game/ui/Deck.ts, client/src/lobby/createGame.ts, server/src/game.go, server/src/game_player.go, server/src/views/main.tmpl
This patch:
* uncomments the AllOrNothing option from the UI
* adds the logic to prevent gameplay after a critical discard or when the next player has no cards and no clues
* disables setting the endTurn variable to prevent the endTurn condition firing
* prevents the "last turn" text from being applied in allornothing games, when there are no more cards in the deck
=> feat: Add AllOrNothing logic to game code

client/src/game/ui/hypothetical.ts, client/src/game/ui/replay.ts, client/src/game/ui/websocket.ts
After the last action is done when playing through past actions, we should always do a cardStatusCheck()
The deleted code in websocket.ts is redundant (and causes lag) because it already happens in the replay.goto function
=> Improve replay loading (fix #1254)

client/src/game/ui/HanabiCard.ts, client/src/game/ui/action.ts
Fix #1302 . Now, cards discarded from your own hand will properly update possibilities on other cards
=> Bugfix for updating card possibilities

public/css/hanabi.css, server/src/views/profile.tmpl
Fixes #1314 . They're all stacked on top of each other because I think it would be weird to have two rows of two buttons each in this layout.
=> Better profile buttons

client/src/game/ui/action.ts
Suppose Bob plays. If you're reading a note on Cathy's hand, you want to keep reading it. If you're reading a note on Bob's hand and the card moves, the note will automatically close when you move your mouse a bit.
=> Don't hide tooltips when a game action happens

client/src/game/ui/action.ts
Reinstate #1327 , but fix the glitch where played/discarded cards continue to appear hidden due to empathy
=> Turn off empathy on played/discarded cards

client/src/game/ui/drawHands.ts
* No changes to the current UI for standard options
* Fix #1331 , at least in BGA mode. Keldon hands might look weird with one less card, but there isn't really a good way to fix that.
=> Fix BGA nameframes

client/src/game/ui/HanabiCard.ts
Should fix the blank cards described in #1351 . I don't really think there's a more efficient way to do this without restructuring everything.
=> Bugfix for setBareImage() optimization

client/src/game/ui/CardLayout.ts
See here https://user-images.githubusercontent.com/32303453/86517915-d7e7fc80-bdfa-11ea-9001-a5e20fae65cf.png The hands need to use proper scaling so that the cards don't bunch together like this.
btw this was original keldon code https://github.com/Zamiell/hanabi-live/blame/9b2a50c21d29131fe27a952b97e06ddba7b51388/public/js/ui.js#L782 maybe back then the cards didn't scale based on the screen resolution?
=> Fix spacing between cards on higher resolutions

server/src/variants_reversible.go
Fix #1193 .... I had a cursory glance of the logic and it seemed correct, so this shouldn't have any negative side effects. It now matches `game.go` line 270
=> End game early with reversed suits

docs/FEATURES.md
It was probably renamed at some point, and the link broke.
=> Fix link to website-endpoints

client/src/game/ui/FullActionLog.ts
Repro: during a replay, open the full action log or a player log, press arrow left/right
Expected: text updated
Actual: text disappears
=> Fix text updates while action log is open

client/src/game/ui/FullActionLog.ts
Repro (before this PR): open a replay, go to last turn, click action log, it's blank.
=> Ensure the action log is shown on first open

client/src/game/ui/arrows.ts
Fix quack arrow graphical glitch (reported on discord...)
=> Ensure the text is hidden when clue is quack

server/src/discord.go
Fixes #1659 
I tested both cases locally. With nickname and without.
=> discord: Reappear Discord usernames for those who don't use a nickname

.vscode/settings.json, client/src/game/ui/keyboard.ts, client/src/lobby/createGame.ts, client/src/lobby/nav.ts, client/src/modals.ts, public/css/hanabi.css, server/src/views/main.tmpl
* Fix #1026
* Keep chat modal open (but I can't figure out a nice way to keep the password box or create game dialog open without looking like there is lag in the no-warning case. perhaps a variable that tracks lastOpenTooltip??)
* Use a solid color instead of letting the wood background bleed through (to undo this, make page-cover have the same properties as body)
* Don't allow clicking on background elements (clicking the background still closes tooltips, not sure why, but we want that)
* Yay for functionizing the code
=> Saner modal backgrounds

client/.eslintrc.js, client/src/game/data/variantsInit.ts, client/src/game/rules/abbreviation.ts, client/src/game/rules/variant.ts, client/src/game/types/Variant.ts, client/src/game/ui/HanabiCardClick.ts, client/src/game/ui/noteIdentityPattern.ts, client/src/game/ui/notes.ts, client/tsconfig.json
This makes the note parsing logic do far less work. This changes behavior in two ways:
- Partial identity notes can now combine, for example `[r] [1]` now produces a morphed red 1
- Abbreviation identity notes can now have a space in the middle, for example `r 1` now produces a morphed red 1
I have tested this locally extensively
=> client: Improve note parsing logic

client/src/game/ui/CardLayout.ts
If user is working hard to hold down space bar or left mouse in a replay while also navigating left/right arrow then they may not want to see the new cards either. This would be a useful change in behavior for me if I want to follow through a replay for practice pretending to be Alice (so I can hold down left mouse button without seeing new cards).
For the record, this is (i) my first pull request, (ii) I wrote it on 0 hours of sleep (insomnia), so if this is a bad idea no need to be polite about it.
=> Respect Empathy when drawing new cards

client/src/modals.ts
otherwise it's buggy; for one dialogs and errors use the same shade which results in behavior like the Create Game dialog over the error message over the page cover
(this is also how it was before my PR)
=> Close dialogs under warnings and errors

client/src/game/ui/LayoutChild.ts, client/src/game/ui/keyboard.ts
Fix #1749 and its parallel - keyboard shortcuts don't work properly when game ends at 0 clues/8 clues
(code copied from 72fe9dc062427e819873830bb1c64156dbe53a7f)
=> Bugfix for hypo acting like game

client/src/game/ui/arrows.ts
Fix #1774 
I believe this has always been a bug, but it's more noticeable now because of the reverse play animations
=> Fix for buggy clue arrows

client/src/game/ui/HanabiCard.ts
=> Show finessed border if note contains both [unclued] and [f]

client/src/game/types/CardNote.ts, client/src/game/ui/HanabiCard.ts, client/src/game/ui/HanabiCardClick.ts, client/src/game/ui/HanabiCardMouse.ts, client/src/game/ui/notes.ts, client/src/game/ui/reactive/view/cardsView.ts
This sets up parsing for identity list notes and causes a note like `g2, r2` to morph the card into a 2.
Resolves #1739 
TODO:
=> Identity list note

client/src/game/ui/notes.ts
=> Fix whitespace after comma in identity list notes

client/src/game/ui/drawHands.ts, client/src/game/ui/drawUI.ts
in keldon mode:
* move hands and labels around so things don't overlap or go offscreen (which they had been doing because of the black bar addition a while ago)
* make the black bar a roundrect, like every other rect on the website.
also, reduce the font size of the replay ID text on the deck by 5%, so that when it says "JSON replay" it no longer runs riiiiiight up to the edge, which was ugly.
=> Tiny tweaks to clean up the ui (mostly keldon mode)

client/src/lobby/tablesDraw.ts
No need to add/remove row mouseover actions all the time; just once when the row is created.
Also the .hover class is redundant but I will remove it after the implementation of server CSS cache busting
=> remove reduntant code

client/src/game/reducers/turnReducer.ts
Fixes https://github.com/Zamiell/hanabi-live/issues/1735
`cardsDiscardedThisTurn` is only used in [shouldEndTurnAfterDraw](https://github.com/Zamiell/hanabi-live/blob/master/client/src/game/rules/turn.ts#L7) when deciding if the panicky player's turn should continue. This change makes sure that this variable is not incremented after a misplay. 
**QA**
- tested that misplaying as panicky with < 5 clues advances turn
- tested that discarding, playing, cluing, and striking advance turn in normal cases
=> only increment discarded cards if not a strike

client/src/game/rules/turn.ts
In the case of a bottom-deck blind-play, a `draw` action occurs that should not end the turn, so the condition of `cardsDiscardedThisTurn !== 1` is insufficient
Fixes #1938
=> Fix panicky Bottom-Deck Blind-Play

client/src/game/rules/card.ts, client/src/game/ui/reactive/view/statsView.ts
Two changes:
* If a card is known (e.g. we are Alice and see it in Bob's hand), then `allPossibilitiesTrash` will just use the known identity instead rather than the clued information. (Thus, trash cards essentially do not need `kt` notes anymore to get the efficiency correct.)
* Don't allow negative future efficiencies.
If a card is duplicated it will still count doubled until one of them plays, alas.
=> Stats minor fix

server/src/chat_general.go
The /new command linked to the old conventions website, this updates the links.
=> Update ref to conventions in bot commands

client/src/game/ui/PlayStack.ts
Right now when a new card is added to the stack `doLayout` is called, which attempts to animate every card on the stack. This causes insane lag when the play stack is large, which is especially notable in Throw It In A Hole where every card is attached to the same stack object.
I don't see why we can't just animate the most recently played card. 
I tested no variant, TIH, spectator, and replay and everything works fine (and with less lag)
=> Fix lag in throw it in a hole 

client/src/game/ui/drawUI.ts, client/src/game/ui/reactive/StateObserver.ts, client/src/game/ui/reactive/view/cardLayoutView.ts, client/src/game/ui/reactive/view/cardsView.ts
#2097 : Unmorphing play stacks at game end by adding a new observer on the "finished" property.
#2098 : Allowing notes on a middle play stack after someone plays a card by creating the invisible "hole" play stack before the regular play stacks, so the "hole" will be behind the middle play stack as opposed to in front of it (so it won't block notes anymore).
=> Fixing notes issues (#2097 and #2098) with throw it in a hole.

server/src/views/history.tmpl, server/src/views/profile.tmpl
To fix the issue described in #2130, I just needed to tell the tablesorter plugin how to parse the date and time values in this column. As explained in the comments, my current fix assumes that the displayed date and time is always in the format `YYYY-MM-DD — hh:mm:ss`. Based on my observation this is true for my local tests as well as for the official website. But I do not know whether this is implicitly (Go/Postgres/...?) or specified somewhere (I didn't found something corresponding). If the date and time string is in another format, sorting will not work (order as returned from backend; behavior is exactly the same as in current productive version).
What do you think? Is there a possibility that the date and time string will have another format? Is this fine or do you have any idea …
=> Fix: make date&time column sortable closes #2130

client/src/globals.ts, client/src/modals.ts
When the user types an invalid command, a modal warning is shown. This fix moves the focus to the "close" button, which can now be closed by pressing ENTER.
After modal close, the focus is set to the last HTML element, which is the appropriate text box.
=> [client] set focus to close button, closes with [ENTER]

client/src/game/ui/drawUI.ts, client/src/game/ui/reactive/view/gameInfoView.ts
When a variant is hard or it's the low score phase, the numbers of the corresponding info are colored.
This PR makes the font also bold if colorblind mode is activated.
=> Make hard variant and low score phase indicators colorblind friendly

client/src/game/ui/Elements.ts, client/src/game/ui/drawUI.ts
I often see that players notice that 1s or 5s are e.g. rainbow only by
the middle of the game
=> Make name of the variant more visible

client/src/game/ui/HanabiCardClickSpeedrun.ts
* Clue correct color when left clicking rainbow cards, properly taking into account the state of the clue interface
* Intentionally send invalid clue when color cluing truly colorless card
#2197
=> Fix left click color clues in speedruns

client/src/chat.ts
I encountered this issue with the auto-scroll:
https://user-images.githubusercontent.com/86917256/124386937-a25b4500-dcd4-11eb-905d-dd5fd4990aaa.mov
It happens only when my browser window is not in full-screen and it fixes itself if I refresh the page. I'm on a MacOS 11.3.1
This could be the issue described in #2078
Basically I noticed that the `scrollHeight - scrollTop` value is 1px bigger than `clientHeight` and it causes the issue. I'm not sure where this pixel comes from (I initially thought it might be the border since it's 1px wide but it's not) so I decided to give it a +-2 px margin to decide if it should auto-scroll. This way it will also work when `scrollTop` is fractional sometimes.
Note: I didn't manage to test this change locally
=> Fix verification if chat needs to scroll

client/src/game/ui/reactive/view/gameInfoView.ts
Fixes (me-made) bug were score is always bold in colorblind mode, instead of being bold only during low score phase.
=> Fix score being permanently bold in colorblind mode

client/src/lobby/createGame.ts
Currently the game's name control has the focus when options are shown. I believe it's much more useful to set the focus to the change variant control, since it's the one changed most often.
=> Focus the Change Variant when game options shown

server/src/command_table_create.go
This PR disables exclamation mark validation when calling `isTableNameValid` from table_create because it was falsely invalidating any table name starting with an exclamation mark. The purpose of the validation is still fulfilled by code later in the function.
=> Fix table creation commands

client/src/game/ui/timer.ts, client/src/misc.ts
Timer calculations now use absolute values given that in non timed games time is measured using negative values.
=> Time display and calculations use absolute values

.env_template, server/src/command_chat.go, server/src/discord.go
Closes #1957
1. **Untested** (but it should work properly)
2. Before server restart, .env must be filled in with the new value
=> Server restart also sent to website-dev channel

client/src/lobby/createGame.ts, client/src/lobby/types/Settings.ts, client/src/types/Options.ts, install/database_schema.sql, server/src/command_replay_create.go, server/src/command_table_update.go, server/src/misc.go, server/src/models_user_settings.go, server/src/options.go
- Max players is now saved in local storage
- During pregame, host can change the max number of players
- During pregame, guests can propose new max players (warning if this is less than the number present ones)
- If new value of Max Players is less than the number present players, extra players are kicked with a message.
=> Max players change option

client/src/game/ui/HanabiCardMouse.ts
Unrelated to latest issue, but still a bug, fixed now.
HanabiCard.id (inherited from Konva.Group) returns a function, not a value.
=> Correctly identify card for empathy cancel

server/src/api_games.go, server/src/api_misc.go, server/src/models_games.go
Closes #2219 
New routes for JSON data, previously served in URLs ending with ?api
Previously: `/history/<name>[/<name>...]?api`
Now: `/api/v1/history-full/<name>[/<name>...]`
Previously: `/seed/[seed]?api`
Now: `/api/v1/seed-full/[seed]`
=> New JSON routes

server/src/chat.go
Closes #2059 
Cannot test (but [code](https://github.com/Hanabi-Live/hanabi-live/blob/bcbe24fe6ef18f1591ffd9aaab68980e3f7bed5b/server/src/chat.go#L93) now fetches the correct user id)
(based on issue screenshot)
=> fix regexp

packages/client/src/game/ui/drawCards.ts
Fix certain combinations: in "Brown-1s & White" w1 is null, but before
it was drawn as brown, which is technically correct but misleading.
=> Darken the dark suit special 1/5

packages/client/src/commands.ts
When `gameID` does not exist in the database, make sure the modal is shown.
=> Close modals before warning

server/src/api_games.go, server/src/api_misc.go, server/src/models_games.go
New optional query parameters `start` and `end` for history-full API.
Example:
`hanab.live/api/v1/history-full/Alice?start=50&end=100` returns the games with IDs between 50 and 100 (including).
Both parameters are optional.
=> Add optional limits to history-full API

packages/client/src/game/reducers/cardPossibilitiesReducer.ts
Fixes this:
so it highlights all odd/even numbers.
Thanks @DrAnax for the help :)
=> Fix highlight in Odds and Evens so it colors all odd/even numbers.

docs/INSTALL.md
Changes sample .ts file from `public\js\src\main.ts` to `Client\src\main.ts` since there is no longer a file at the first location
=> Update sample .ts file

packages/client/src/lobby/lobbyCommands.ts, packages/client/src/lobby/nav.ts, packages/client/src/lobby/pregame.ts, packages/client/src/lobby/tablesDraw.ts, packages/client/src/lobby/types/Table.ts, public/css/hanabi.css, public/img/hover-cursors/icons.svg, server/src/command_table_create.go, server/src/command_table_join.go, server/src/command_table_leave.go, server/src/command_table_spectate.go, server/src/command_table_start.go, server/src/command_table_unattend.go, server/src/session_notify.go, server/src/table_notify.go, server/src/views/main.tmpl
Closes #1253 
Addresses #2553 
Closes #2605 
- Fixed asking for cursor image each time (svg in css file)
- Replaced creepy eye cursor with beloved googly eyes
- In lobby: click the spectators column on a pregame to join as a spectator
- In pregame: notifications when players join game or spectators join table
- In pregame: when table owner leaves, ownership is passed on to the next of kin
=> Table spectators, owners and beautiful eyes

.gitignore, packages/client/src/game/ui/HanabiCard.ts, packages/client/src/game/ui/HanabiCardClick.ts, packages/client/src/game/ui/notes.ts, packages/data/src/abbreviations.ts
* Fixed bug created by HTML parsing notes: "<foo" would not show anything.
* Fixed bug with meaningful notes getting surrounded by brackets: "[k3] some text" -> "[[k3] some text] [cm]"
* Added automated turn count to notes with ctrl + alt + right-click
=> Note bug fixes, turn count added

docs/VARIANTS.md
The 5 suit colours are listed in the old order (before they were made into rainbow order rygbp). Probably doesn't matter, but thought I'd point it out and fix it when I saw it.
=> VARIANTS.md: fix suit order

packages/client/src/game/reducers/notesReducer.ts, packages/client/src/game/types/SpectatorNote.ts, packages/client/src/game/types/actions.ts, packages/client/src/game/ui/gameCommands.ts, packages/client/src/game/ui/notes.ts, public/css/hanabi.css, server/src/command_chat.go, server/src/command_chat_read.go, server/src/command_chat_typing.go, server/src/command_get_game_info_1.go, server/src/command_get_game_info_2.go, server/src/command_note.go, server/src/command_replay_action.go, server/src/command_table_restart.go, server/src/command_table_spectate.go, server/src/command_table_start.go, server/src/command_table_unattend.go, server/src/game_end.go, server/src/http_localhost_clear_empty_tables.go, server/src/print.go, server/src/session_notify.go, server/src/spectator.go, server/src/table.go, server/src/table_notify.go, server/src/tables.go, server/src/websocket_disconnect.go
Saving spectatornotes even if they change table.
Visually differenciate them from players notes.
Don't save spectators notes in the database.
=> Save spectator notes

packages/client/src/game/rules/hGroup.ts
They are no longer hard variants.
=> fix: eff counter colour for null/dark null

packages/client/src/game/reducers/initialStates/initialGameState.ts, packages/client/src/game/reducers/statsReducer.ts, packages/client/src/game/rules/stats.ts, packages/client/src/game/types/StatsState.ts, packages/client/src/game/ui/reactive/StateObserver.ts, packages/client/src/game/ui/reactive/view/statsView.ts
Closes #2519. I checked and the display seems fine if the number is an
integer (no trailing ".0") so I don't know why the Math.floor was there
to begin with, to be honest
(The Math.floor was introduced in 34ebfcfdf.)
=> Don't round down cluesStillUsable

server/src/command_note.go, server/src/table.go
Realized we are escaping the wrong message when storing a new note.
Also removes a leftover debug line
=> Patches a typo in CommandNote

server/src/command_table_spectate.go
If a player is already spectating another table. Kick them from that table, and spectate this new one.
If they are spectating this table. No warning is nessessary
=> Removing "Already spectating" warnings

packages/client/src/game/ui/drawUI.ts
- Anyone can already use /setLeader chat command. Let's make it easier by letting anyone click the crown to change leader.
- Closes #2642
=> Let anyone set leader

packages/client/src/game/ui/HanabiCard.ts
If the card is known to be trash, there is no use to view the dda icon. So we view it only if not known trash
Closes #2762
=> Prioritize mini trash before dda

server/src/game_end.go
Players need to be deletes from playing tabke relationship even if they are not present at the table when it terminates.
Closes #2758
=> Update Playing relationship of players not present

packages/client/src/game/reducers/stateReducer.ts
When a default game action is happening in stateReducer, it is never in hypo. Hypo is handeled in the replayReducer
- Closes #2757
=> Fixes log hypo prefix

server/src/command.go, server/src/command_table_create.go, server/src/command_table_join.go, server/src/command_table_restart.go
Closes #2683
I decided not to implement the thing that makes spectators join as
players because of Krycke's comment in #2683. (Indeed, seems wrong to
me in at least one case: if I'm say playing a game with some friends
that's pw-protected, and I restart the game, the random specs watching
that didn't enter a password probably shouldn't be joined.) So I'm gonna
say someone should open a new issue describing what the "correct"
behavior should be.
=> Preserve password on remake table

packages/client/src/game/ui/HanabiCardClick.ts
One some Mac devices, right-click is not available to open the tooltip (an external mouse has to be used).
Since this is the default alternative on Mac, we should support this as well.
Also see issue #2837.
=> Support Ctrl + left-click to open note tooltip

cspell.json, install/database_schema.sql
This adds a trigger to the `game_participants` table so that whenever a participant of a game is deleted
(this already automatically happens whenever a user is deleted), the corresponding game is deleted as well.
Some details:
Implementation is the same as https://stackoverflow.com/questions/30281819/postgresql-delete-trigger. I suppose because the code snippet is so short, this does not cause copyright issues. If you think so, we could e.g. put a link into the source code to StackOverflow, but I don't think it's needed.
Also, not that we could e.g. add more checks such that also after each update or insert to the game_participants table (or the games table even), we check that there is the correct number of participants in the database, but this would be more work (I currently don't know …
=> DB: Delete games upon participant deletion

server/src/api_misc.go
This ensures that whenever we query data for the API, the resulting requested sort is deterministic,
therefore yielding disjoint outputs when data is queried with limit and offset (which is done regularly for the API to keep answers at a reasonable size).
Note that even though it is weird, it is still defined to query something like `ORDER BY id ASC, id DESC` in PostgreSQL, the secondary order in that case just won't matter: The ORDER BY clause works with lexicographic order.
See issue #2842 as well.
=> API: Add secondary sort column id to all queries

packages/client/src/game/reducers/gameStateReducer.ts, packages/client/src/game/rules/playStacks.ts, packages/client/src/game/ui/Elements.ts, packages/client/src/game/ui/HanabiCard.ts, packages/client/src/game/ui/drawUI.ts, packages/client/src/game/ui/reactive/StateObserver.ts, packages/client/src/game/ui/reactive/view/cardLayoutView.ts, packages/data/src/getVariantDescriptions.ts, packages/data/src/json/variants.json, packages/data/src/types/Variant.ts, packages/data/src/types/VariantDescription.ts, packages/data/src/types/VariantJSON.ts, packages/data/src/variantsInit.ts
Fixes #2852.
In particular, gets rid of all the UI code related to the second label row below the stacks, since we don't need these anymore. Also simplifies logic, since we don't have to do anything special in Keldon mode.
=> Rework Sudoku UI

packages/client/src/game/ui/reactive/view/cardLayoutView.ts
Client sometimes showed 0 as stack start immediately after the first card of a stack played. Probably this is due to visibleRank not being updated properly before drawing the UI (the bug seems to occur a bit random), but getCardIdentity does not have this issue.
See also #2859
=> Client: Sudoku: Fix UI bug showing 0 as stack start

packages/client/src/game/rules/variants/reversible.ts, packages/client/src/game/rules/variants/sudoku.test.ts, packages/client/src/game/rules/variants/sudoku.ts
This cleans up some of the Sudoku code as requested:
- Removes null-assertion operator, instead uses a combination of `assertDefined` and more specific types to ensure safe index access.
- Clarifies the suitMaxScores variable, which was confusing before
- Fix a bug in the sudoku score calculation:
- If both copies of a 5 were discarded, this caused wrong calculations on the maximum possible score.
- This bug was introduced 1bd3fc87, since previously, the iterated range might have been empty when `lastDead +1 > 5` (which happens when both copies of a 5 have been discarded, but the `iRange` macro that had been introduced returns a reverse range in this case.
- In general, I think that this usage behaviour feels very dangeruous to me. While it is documented, i would expect something like …
=> Clean up sudoku

docs/chat-commands.md, packages/client/src/chatCommands.ts, server/src/chat_command.go, server/src/command.go, server/src/command_chat_link.go
People pointed out to me that this is probably the better naming. I'd suggest to keep /links as a (client-side) alias, so we'll just have both.
=> rename command: links -> linked

packages/client/src/chatCommands.ts
When refactoring this was broken, doing `/pm Alice hi` results in `Alice hi` being written to Alice.
=> Bugix pm command: pass correct message

packages/client/src/game/rules/deck.ts
Now that there is dark suits combined with Up or Down, we need to adapt the implementation to it, since there is now 6 cards of a dark suit in such a variant.
Since allowing this variant wasn't something I thought about a lot, I didn't think of it before. Also, there's nothing else I know about right now that we need to adapt about the rest of the code.
=> Bugfix: Total number of cards in Up or Down + Dark Suit

server/src/chat_pregame.go, server/src/constants.go, server/src/game.go, server/src/http_stats.go, server/src/http_sub.go, server/src/variant.go, server/src/variants.go, server/src/variants_reversible.go, server/src/variants_sudoku.go
Turns out the server did not have a sense of different stackSizes and therefore scores thus far, which is in particular why the stats page was bugged and it showed 20 for Sudoku 4 suits.
Variants already had a property `maxScore`, but it was not used consistently, I refactored (hopefully) all the usages to use `variant.maxScore` now when appropriate and set this value accordingly at initialization. Same goes for `stackSize`, which is added now as an additional attribute and used in the Sudoku code for more clarity.
I did a test game locally and it shows Sudoku correctly now on the stats page, the checkmark also works.
=> server: add stackSize to variants, refactoring

server/src/variant.go
This now mimics the implementation from the client. For gameplay, this did not cause issues, but creating JSON replays for the new variants is not possible without this fix, since the server complains about wrong numbers of cards.
=> server: Fix GetDeckSize() method

packages/game/src/rules/variants/sudoku.ts
This also fixes a bug: In Sudoku 4-suit, the minimum should be taken with variant.stackSize, not with just the default number of suits.
=> SLR: Clean up Sudoku code

packages/client/src/lobby/createReplayJSON.ts
This fixes the bug introduced in ad384ac during refactoring, where the `startsWith` method was replaced with an exact match.
=> fix parsing colors in hypos

packages/client/src/commands.ts
should resolve #2940 
Tested locally:
receiving a pm in game -> now the number shows up next to the chat icon
receiving a normal in game message -> still get a number showing up
receiving a normal message and pm in global lobby -> no errors in console
=> Make PMs received during games display a chat notification in the bottom left

packages/client/src/lobby/url.ts
When pre-game url is opened - send join request with stored join password.
I play hanabi mostly with my friends on password
protected tables. Every time I open the pre-game link, It tells me: "That is not the correct password for the game". I didn't provide any password, yet. But the game gives me an error message.
This PR fixes my use case, and doesn't break games without passords Tested this way (U1, U2 - users):
1. U1: Create game without password.
2. U2: Join the pre-game link
3. U1, U2 leave table
4. U1: Create password protected game
5. U2: Join the pre-game link. Notice the wrong password message
6. U2: Enters password, successfully joins the table
6. U1, U2 leave game
7. U1: Create password proteced game. (Same password)
8. U2: Join the pre-game link. **No errors**
9. U1, U2 leave …
=> Join pre-game with stored join password

packages/server/src/templates/main.eta, server/src/views/main.tmpl
After players learn H-group, a good number are also interested in H-group spinoffs and other convention systems. And some of those curious will check out the list of resources too, so I suggest including hanabi.wiki as well.
=> Add hanabi.wiki to the list of resources

packages/client/src/game/ui/ButtonGroup.ts
The selectNextTarget() function had a logical bug where it was using a for...of loop while incrementing a separate buttonIndex variable, causing it to skip buttons and fail to cycle properly through players.
Fixed by replacing the flawed loop with a for loop using modulo arithmetic:
- Uses (buttonIndex + i) % total pattern for circular iteration
- Properly cycles through all button indices in order
- Only selects enabled buttons
This resolves the issue where Tab key player cycling would only work once or sporadically instead of cycling through all available players.
=> fix: correct player cycling logic in Tab key shortcut
