- src/variants.go
Completely rewrote the guts of variants.go to eliminate lots of if
statements and magic number. This time with IsOneOfEach defaulted
> Refactored variants.go

- public/js/src/game/ui/HanabiCard.js
Middle clicking a card goes to the turn it was first positively clued, not also negatively.
> Middle click positively clued turn

- scripts/python/dump_game.py
Still lots more features to add, and ideas to describe for improving game record format, but here's a start.
> Add dump_game.py for dumping game records

- docs/FEATURES.md
- public/js/src/game/ui/drawUI.ts
See https://github.com/Zamiell/hanabi-live/issues/852.
> Fix documentation on "efficiency" in FEATURES.md and UI tooltip.

- public/js/src/game/ui/timer.ts
I did not check whether this code works or compiles.
Closes #815.
> Disable player time tooltip in speedrun games

- .dockerignore
- .gitignore
- Dockerfile
- docker-compose.yml
- docs/INSTALL.md
Usage: `docker-compose up --build`.
> add Dockerfile and docker-compose.yml

- public/js/src/game/ui/FullActionLog.ts
- public/js/src/game/ui/MultiFitText.ts
Resolves #1076 
Screenshot:
[![screenshot showing message][screenshot]][screenshot]
[screenshot]: https://i.imgur.com/E7saMJt.png
> ui: Add message for when a player's action log is empty

- src/variants_reversible.go
> Fix condition that differentiates up or down from reversed for max score

- public/js/src/game/ui/HanabiCard.ts
- public/js/src/game/ui/HanabiCardInit.ts
Fixing overlaps between note and rank pips in empathy
> Move note back to top/right and crit to bottom/left

- public/js/src/constants.ts
- public/js/src/game/ui/Clue.ts
- public/js/src/game/ui/Deck.ts
- public/js/src/game/ui/HanabiCard.ts
- public/js/src/game/ui/HanabiCardClickSpeedrun.ts
- public/js/src/game/ui/LayoutChild.ts
- public/js/src/game/ui/MsgClue.ts
- public/js/src/game/ui/SimpleCard.ts
- public/js/src/game/ui/State.ts
- public/js/src/game/ui/action.ts
- public/js/src/game/ui/actions.ts
- public/js/src/game/ui/arrows.ts
- public/js/src/game/ui/clues.ts
- public/js/src/game/ui/convert.ts
- public/js/src/game/ui/drawUI.ts
- public/js/src/game/ui/globals.ts
- public/js/src/game/ui/hypothetical.ts
- public/js/src/game/ui/keyboard.ts
- public/js/src/game/ui/replay.ts
- public/js/src/game/ui/turn.ts
- public/js/src/game/ui/variants/reversible.ts
- public/js/src/game/ui/websocket.ts
Fixes #1153 
Also changed some interfaces to straight up types. Didn't do this replacement everywhere though.
Main benefit: now actions are strongly typed, so it won't compile with typos on action names.
> Make actions and constants strongly typed. No functional changes

- public/js/src/game/ui/SimpleCard.ts
- public/js/src/game/ui/actions.ts
- public/js/src/game/ui/hypothetical.ts
Went a bit overboard with type aliases
> Change simple type aliases back to interfaces

- client/src/game/ui/HanabiCard.ts
> Critical indicators also show in empathy and while dragging if the card is known

- client/src/game/ui/action.ts
- client/src/game/ui/actions.ts
- client/src/game/ui/hypothetical.ts
- client/src/game/ui/replay.ts
- client/src/game/ui/stateChange.ts
- server/src/actions.go
- server/src/table_notify.go
Fix #1182 - It has a bug sometimes counting the clues and/or the cards left on deck
> Trust the server for clues, but log errors if the client state differs

- client/package-lock.json
- client/package.json
- client/src/game/ui/action.ts
- client/src/game/ui/globals.ts
- client/src/game/ui/stateChange.ts
- client/src/game/ui/websocket.ts
Also calculate score as it goes (score shouldn't be necessary on status)
No functional changes.
> Make state changes pure using Lodash

- docs/CHAT_COMMANDS.md
proposing to make it clear that you'll get an integer if you use random
> /random returns an integer

- client/package-lock.json
- client/package.json
- client/src/game/ui/State.ts
- client/src/game/ui/globals.ts
- client/src/game/ui/replay.ts
- client/src/game/ui/stateChange.ts
- client/src/game/ui/websocket.ts
Without any functional changes or side effects changes
> Re-implement basic state machine changes

- client/src/game/ui/replay.ts
- client/src/game/ui/stateChange.ts
- client/src/game/ui/websocket.ts
Eventually we will only use states and not actions for replays, so this will go away.
> Don't rehydrate state in replays for now.

- client/src/game/ui/arrows.ts
For now. Later, should change all which to button or buttons.
> Fix #1210 - Revert to evt.which

- client/src/chatCommands.ts
- docs/CHAT_COMMANDS.md
- server/src/command.go
- server/src/command_chat_playerinfo.go
Text is
> "padi" has played 0 non-speedrun games. More stats here.
where More stats here is a link to the relevant /scores page
> Add /playerinfo command

- client/src/game/rules/deck.test.ts
- client/src/game/rules/hand.ts
- client/src/game/rules/variant.test.ts
- client/src/game/rules/variant.ts
- client/src/game/types/CardState.ts
- client/src/game/ui/Elements.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/HanabiCardClick.ts
- client/src/game/ui/HanabiCardClickSpeedrun.ts
- client/src/game/ui/HanabiCardInit.ts
- client/src/game/ui/HanabiUI.ts
- client/src/game/ui/LayoutChild.ts
- client/src/game/ui/PlayStack.ts
- client/src/game/ui/action.ts
- client/src/game/ui/clues.ts
- client/src/game/ui/drawCards.ts
- client/src/game/ui/drawUI.ts
- client/src/game/ui/hypothetical.ts
- client/src/game/ui/notes.ts
- client/src/game/ui/replay.ts
- client/src/game/ui/turn.ts
- client/src/game/ui/variants/reversible.ts
Move CardState to types
Add variant pure functions (+ tests)
> Graft card state out of HanabiCard

- .vscode/settings.json
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/action.ts
- client/src/game/ui/globals.ts
- client/src/game/ui/hypothetical.ts
- client/src/game/ui/websocket.ts
Now the toggle behaves properly
> Fix hypoRevealed

- client/src/chatCommands.ts
- client/src/game/ui/drawUI.ts
- client/src/game/ui/hypothetical.ts
- client/src/game/ui/websocket.ts
* No longer need to right click the crown for it to work, any old click will do
* Fix #1260
> Improve switching the leader

- client/src/game/types/CardIdentity.ts
- client/src/game/ui/HanabiCardClick.ts
- client/src/game/ui/notes.ts
> Better notes

- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/action.ts
- client/src/game/ui/drawUI.ts
Noted cards now get arrows, and also fixes #1198
> Better card arrows

- server/src/command_table_set_variant.go
> Fix /changevariant user stats

- client/src/game/ui/ColorButton.ts
- client/src/game/ui/CurrentPlayerArea.ts
- client/src/game/ui/Deck.ts
- client/src/game/ui/HanabiUI.ts
- client/src/game/ui/NameFrame.ts
- client/src/game/ui/drawReplayArea.ts
- client/src/game/ui/drawUI.ts
Basically, this fixes the thick and ugly black borders on smaller screens
> Better scaling

- client/src/game/reducers/gameStateReducer.test.ts
- client/src/game/reducers/gameStateReducer.ts
- client/src/game/reducers/initialState.ts
- client/src/game/reducers/replayReducer.test.ts
- client/src/game/reducers/replayReducer.ts
- client/src/game/reducers/stateReducer.ts
- client/src/game/types/ReplayState.ts
- client/src/game/types/State.ts
- client/src/game/types/actions.ts
- client/src/game/ui/replay.ts
- client/src/game/ui/websocket.ts
- client/src/misc.ts
- client/test/loadGameJson.ts
- client/test_data/test_game.json
+ separate replay processing in its own reducer
+ basic tests for hypothetical
> Add hypothetical support to reducers

- client/src/game/reducers/gameStateReducer.test.ts
- client/src/game/reducers/replayReducer.test.ts
- client/test/testActions.ts
The main attribute of a good test is that you can read it and understand it without looking at the code being tested, or the implementation of other helper functions.
> Make state tests compact and DRY

- client/src/game/ui/ColorButton.ts
- client/src/game/ui/Deck.ts
- client/src/game/ui/HanabiUI.ts
- client/src/game/ui/NameFrame.ts
- client/src/game/ui/controls/CurrentPlayerArea.ts
- client/src/game/ui/drawReplayArea.ts
- client/src/game/ui/drawUI.ts
Specifically, zam's canvas which is 947 pixels high
> Revert scaling changes to match old UI on a 1080p screen

- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/action.ts
- client/src/game/ui/replay.ts
Also should fix the issue where for example in this review http://hanabi.live/replay/214544/24 the g3 is marked as not 4 and not 1 because pablo himself drew g4 and g1.
> Split card.reveal() functionality into convert()

- maintenance/index.html
- public/css/hanabi.css
- server/src/views/informational.tmpl
- server/src/views/main.tmpl
- server/src/views/profile.tmpl
- server/src/views/stats.tmpl
- server/src/views/variant.tmpl
> Better mobile nav bar; Hanabi Live is now a link in header

- client/src/game/ui/HanabiCardInit.ts
> Bugfix for viewing empathy after a game action

- client/src/game/ui/HanabiCard.ts
Fix #1328 (but not serverside)
> Hotfix for cards showing in Throw It in a Hole

- client/src/game/ui/notes.ts
> Hide special borders on played/discarded cards

- client/src/game/reducers/replayReducer.test.ts
The beforeEach method was running before every test, not just the ones in this file.
> Improve test performance by only loading the game JSON once

- client/src/game/ui/replay.ts
> Fix state turn going out of sync on game over

- client/src/game/reducers/replayReducer.test.ts
- client/src/game/reducers/replayReducer.ts
- client/src/game/types/actions.ts
- client/src/game/ui/gameCommands.ts
- client/src/game/ui/replay.ts
- client/test/testActions.ts
> Add starting turn to startReplay action

- client/src/game/reducers/gameStateReducer.test.ts
- client/src/game/reducers/gameStateReducer.ts
- client/src/game/types/GameState.ts
- client/src/game/ui/FullActionLog.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/PlayStack.ts
- client/src/game/ui/action.ts
- client/src/game/ui/hypothetical.ts
- client/src/game/ui/reactive/StateObserver.ts
- client/src/game/ui/reactive/view/cardLayoutView.ts
- client/src/game/ui/reactive/view/logView.ts
- client/src/game/ui/replay.ts
+ Breaks animations
+ Fix stack directions
> Fix layout of discard/playstacks/hands by hiding and showing at the right time

- client/src/game/ui/CardLayout.ts
- client/src/game/ui/ClueEntry.ts
- client/src/game/ui/ColorButton.ts
- client/src/game/ui/Deck.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/PlayStack.ts
- client/src/game/ui/RankButton.ts
- client/src/game/ui/action.ts
- client/src/game/ui/arrows.ts
- client/src/game/ui/controls/Button.ts
- client/src/game/ui/drawLayer.ts
- client/src/game/ui/konvaHelpers.ts
- client/src/game/ui/pause.ts
- client/src/game/ui/reactive/StateObserver.ts
- client/src/game/ui/reactive/observeStore.ts
- client/src/game/ui/reactive/view/cardLayoutView.ts
- client/src/game/ui/replay.ts
- client/src/game/ui/timer.ts
+ Konva Tween helper ensuring fewer leaks and fewer mouse events
> Add misplay animation, fix many animation issues

- client/src/game/ui/CardLayout.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/PlayStack.ts
- client/src/game/ui/arrows.ts
- server/src/variants_reversible.go
> Fix card arrows are not in the right spots #1414

- client/src/game/reducers/initialStates/initialState.ts
- client/src/game/reducers/stateReducer.test.ts
- client/src/game/reducers/stateReducer.ts
- client/src/game/types/State.ts
- client/src/game/ui/gameCommands.ts
- client/src/game/ui/reactive/StateObserver.ts
- client/src/game/ui/reactive/observeStore.ts
- client/src/game/ui/reactive/view/cardLayoutView.ts
- client/src/game/ui/reactive/view/cardsView.ts
- client/src/game/ui/reactive/view/initView.ts
- client/src/game/ui/replay.ts
Fix #1413
+ A nicer syntax for subscribing to visibleState changes (most common)
+ Tests
> Don't animate while initializing

- client/src/game/reducers/cardPossibilitiesReducer.test.ts
Hopefully I did it correctly this time :)
> Card reducer

- client/src/game/ui/ClueEntry.ts
- client/src/game/ui/FullActionLog.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/HanabiCardInit.ts
- client/src/game/ui/LayoutChild.ts
- client/src/game/ui/PlayStack.ts
- client/src/game/ui/controls/FitText.ts
- client/src/game/ui/cursorSet.ts
- client/src/game/ui/drawCards.ts
- client/src/game/ui/drawUI.ts
- client/src/game/ui/gameCommands.ts
- client/src/game/ui/hypothetical.ts
- client/src/game/ui/reactive/view/cardsView.ts
- client/src/game/ui/reactive/view/cluesView.ts
- client/src/game/ui/uiInit.ts
Bugs related to: ClueEntry not working, listening issues, make FitText faster with a binary search
Perf suffers from the shadows, I'll investigate before moving forward with this. But it does look good :)
> Add shadow effects, remove textured backgrounds + other bugs

- client/src/game/reducers/cardsReducer.test.ts
- client/src/game/reducers/stateReducer.ts
- client/src/game/rules/applyClueCore.ts
- client/src/game/types/actions.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/gameCommands.ts
> Fix bug on terminate + bug when a card is clued and gets mouse over

- client/src/game/reducers/initialStates/initialGameState.ts
- client/src/game/rules/playStacks.test.ts
- client/src/game/rules/playStacks.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/HanabiCardInit.ts
- client/src/game/ui/controls/RankPip.ts
Fix #1490, makes progress on #1491 (IMO fixed, but you judge @Zamiell )
Also fixed a Reversed variant bug (+ added tests)
> Improved number pips and X's, improved shadows, no blur on card shadows

- client/src/game/reducers/cardsReducer.ts
- client/src/game/reducers/gameStateReducer.ts
- client/src/game/reducers/stateReducer.ts
- client/src/game/rules/stats.ts
- client/src/game/rules/text.ts
- client/src/game/ui/CardLayout.ts
- client/src/game/ui/Elements.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/drawUI.ts
- client/src/game/ui/gameCommands.ts
- client/src/game/ui/reactive/StateObserver.ts
- client/src/game/ui/reactive/view/cardLayoutView.ts
- client/src/game/ui/reactive/view/gameInfoView.ts
> Fix Throw it in a Hole

- client/src/game/ui/Deck.ts
> Fix bottom deck blind play animation

- client/src/game/ui/reactive/StateObserver.ts
This should fix what's left for #1385
> Fix throw it in a hole glitch by signaling the game is converted to all observers

- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/HanabiCardInit.ts
> Fix shadow redraw by not using sceneFunc to change shadow

- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/controls/RankPip.ts
> Set RankPips to the suit color if available

- .cspell.json
- client/src/game/ui/drawReplayArea.ts
- client/src/game/ui/reactive/view/animateFastView.ts
- client/src/game/ui/replay.ts
+ Fix #1508 
+ Animate fast when the game is over (Fix #1385)
+ Add mouse wheel events over replay area!
> Make dragging replay shuttle animate fast + more responsive

- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/konvaHelpers.ts
- client/src/game/ui/reactive/view/cardsView.ts
+ Last bugs for card-reducer!
+ Fix #1535 #1518 #1488 !
> Fix animation shadows and tweening

- public/css/lib/alpha.css
- server/src/views/history.tmpl
- server/src/views/profile.tmpl
https://github.com/Zamiell/hanabi-live/issues/1544
Also made the input field for score a number input instead of a text input because I noticed it. Feel free to cherry-pick `1a1c0dc` if you just want the bugfix.
> Fix issue 1544

- client/package.json
- client/src/game/reducers/stateReducer.ts
- client/webpack.config.js
200x performance increase for reducers! pogchamp
> Ensure immer auto-freezes deeply recursive structures + proper sourcemaps for libs

- client/src/game/ui/HanabiCard.ts
HanabiCardInit.ts got merged in wrong to card-reducer, so i'm just adding back the touch actions code from https://github.com/Zamiell/hanabi-live/commits/79760aca3cc099e7cd9782bda33dbfbc40a29a04/client/src/game/ui/HanabiCardInit.ts
* Fix #1553
> Add back touch actions

- client/src/constants.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/LayoutChild.ts
Fix #1566 and likely fix #1567
> Fix border and offset bugs + faded X opacity

- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/cursorSet.ts
> Fix raised card. Change hand to OS pointer

- client/src/game/ui/HanabiCard.ts
> Don't show notes on morphed cards

- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/konvaHelpers.ts
> Fix raising bug and Konva error

- client/src/game/ui/FullActionLog.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/HanabiCardInit.ts
- client/src/game/ui/drawUI.ts
- client/src/game/ui/gameCommands.ts
- client/src/game/ui/globals.ts
- client/src/game/ui/notes.ts
- client/src/game/ui/reactive/StateObserver.ts
- client/src/game/ui/reactive/view/cardsView.ts
- client/src/game/ui/uiInit.ts
This reduces loading times (drawing cards etc.) by more than 50%, by only constructing elements when absolutely necessary
> Cut loading times by lazy initializing

- client/src/game/ui/HanabiCardInit.ts
Probably fixes #1621  (unverified)
> Ensure logic doesn't touch the original pips after cloning

- client/src/game/reducers/stateReducer.ts
> Rehydrate scrubbed draws after the game

- client/src/game/ui/HanabiUI.ts
- client/src/game/ui/globals.ts
> Resize canvas when the window changes size

- server/src/discord.go
> discord: Fix nickname behavior and improve approach to Guild Member and Channel resolution

- server/src/game_end.go
- server/src/http_shared_missing_scores.go
- server/src/models_user_stats.go
> Improve shared missing scores

- server/src/http_shared_missing_scores.go
> server: shared missing scores: Fix operand order for IsBetterThan invocation

- client/src/game/ui/reactive/StateObserver.ts
- client/src/game/ui/reactive/view/cardsView.ts
Should fix #1681. I haven't tested this because playing a game locally isn't working well and due to #1696 I can't open the test case replay
> client: card status: Update visisble card status whenever a clue is given

- client/src/game/ui/HanabiCard.ts
Fixes #1693 
This worked locally
> client: card status: Do not fade if card has chop moved note

- client/src/game/ui/HanabiCard.ts
> client: Have finesse border take precedence over chop move border

- client/src/game/ui/noteIdentityPattern.ts
Unfortunately I can't save the file without it auto-formatting that line to be too long.
> client: Use null coalescing to shorten some code

- client/src/game/ui/drawPip.ts
- public/img/pips/triangle.svg
In order to make it look less like the yellow pip.
> Vertically flip prism pip

- client/src/game/rules/stats.ts
> Fix DDA notification

- client/src/game/ui/hypothetical.ts
- server/src/command_replay_action.go
Fix #1747 ; I hope this is the correct way
> Initialize hypo toggleRevealed correctly

- client/src/game/ui/turn.ts
i don't think anything else got borked in the refactor 4eaea506ba159d27e6a024dcaedc74ab45d1acaf
> Bugfix for pre-discard

- client/src/game/ui/HanabiCard.ts
> Ignore chop moved notes w.r.t card fade during postgame

- client/src/game/ui/drawHands.ts
- client/src/game/ui/drawUI.ts
> More element scaling fixes

- server/src/command_table_create.go
Implement #1760 
At start of game, send a chat saying "<username> created a table".
> Implement #1760

- client/src/game/reducers/initialStates/initialGameState.ts
- client/src/game/reducers/integration.test.ts
- client/src/game/reducers/statsReducer.ts
- client/src/game/rules/clueTokens.ts
- client/src/game/rules/deck.ts
- client/src/game/rules/hand.ts
- client/src/game/rules/stats.test.ts
- client/src/game/rules/stats.ts
- client/src/game/rules/variants/reversible.ts
- client/src/game/types/StatsState.ts
- client/src/game/ui/drawHands.ts
- client/src/game/ui/drawUI.ts
- client/src/game/ui/reactive/view/statsView.ts
- client/test/loadGameJSON.ts
Tested it and it seems to work correctly in a 2 player no variant game. It is very disturbing though to have my efficiency be 0.45 during a game....
> Timo future eff

- client/src/game/reducers/initialStates/initialGameState.ts
- client/src/game/reducers/statsReducer.ts
- client/src/game/rules/clueTokens.ts
> Fix clue starved future efficiency

- client/src/game/rules/stats.ts
> Fix future efficiency with negative pace

- client/src/game/rules/stats.ts
- client/src/game/ui/Elements.ts
- client/src/game/ui/drawUI.ts
- client/src/game/ui/reactive/StateObserver.ts
- client/src/game/ui/reactive/view/statsView.ts
- client/src/tooltips.ts
- public/css/hanabi.css
> Show max rounds left and other statistics on turn number hover

- client/src/game/ui/CardLayout.ts
- client/src/game/ui/arrows.ts
- client/src/game/ui/reactive/view/currentPlayerAreaView.ts
> Arrow rotation

- client/src/game/reducers/initialStates/initialGameState.ts
- client/src/game/reducers/statsReducer.ts
- client/src/game/rules/stats.test.ts
- client/src/game/rules/stats.ts
- client/src/game/types/StatsState.ts
- client/src/game/ui/reactive/StateObserver.ts
- client/src/game/ui/reactive/view/statsView.ts
- client/src/game/ui/stats.ts
> Ignore clues from pre-final round discards

- client/src/game/reducers/initialStates/initialGameState.ts
- client/src/game/reducers/statsReducer.ts
and consequently fix DDA sounds.
Still testing locally.
> Fix statsReducer to only be concerned with relevant action types

- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/HanabiCardClick.ts
- client/src/game/ui/noteIdentity.ts
- client/src/game/ui/notes.ts
> Refactor notes

- .vscode/tasks.json
usable from main menu -> Terminal -> Run Task
> add vscode tasks to run client and server

- .vscode/tasks.json
- client/src/game/reducers/initialStates/initialGameState.ts
- client/src/game/reducers/statsReducer.ts
- client/src/game/rules/stats.test.ts
- client/src/game/rules/stats.ts
> Throw-it-in-a-Hole efficiency

- client/src/game/ui/reactive/view/currentPlayerAreaView.ts
> Fix arrow rotation for own player in keldon mode

- client/src/game/ui/reactive/view/hypotheticalView.ts
> Fix ending hypo at 0 clues

- client/src/lobby/tablesDraw.ts
- public/css/hanabi.css
Removed unecessary hover class and the unecessary hidden button used for alt+j shortcut (used a class on the first table row)
> remove redundant css and hidden button

- client/src/game/ui/reactive/view/hypotheticalView.ts
> Fix clue UI and turn indicator being hidden by default

- client/src/game/reducers/cardsReducer.ts
- client/src/game/reducers/gameStateReducer.ts
- client/src/game/reducers/initialStates/initialState.ts
- client/src/game/reducers/notesReducer.ts
- client/src/game/reducers/stateReducer.ts
- client/src/game/types/NotesState.ts
- client/src/game/types/actions.ts
- client/src/game/ui/gameCommands.ts
- client/src/game/ui/globals.ts
- client/src/game/ui/reactive/StateObserver.ts
- client/src/game/ui/reactive/view/statsView.ts
- client/src/game/ui/stats.ts
- client/test/loadGameJSON.ts
Refactor eff mod into notes state.
Also fix the quirk I mentioned about notes modifier being stored in memory during replays (now it always shows "-" instead).
> Note eff mod followup

- client/src/game/reducers/replayReducer.ts
- client/src/game/ui/hypothetical.ts
- client/src/game/ui/reactive/StateObserver.ts
- client/src/game/ui/reactive/view/hypotheticalView.ts
- client/src/game/ui/reactive/view/turn.ts
Fix #1941 and fix #1942 
This also refactors `hypotheticalView` into several smaller functions
> Refactor hypotheticalView and fix two issues

- client/src/commands.ts
- client/src/game/ui/Deck.ts
- client/src/game/ui/HanabiUI.ts
- client/src/game/ui/drawUI.ts
- client/src/game/ui/keyboard.ts
- client/src/game/ui/reactive/StateObserver.ts
- client/src/game/ui/reactive/view/currentPlayerAreaView.ts
- client/src/game/ui/reactive/view/gameInfoView.ts
- client/src/game/ui/reactive/view/hypotheticalView.ts
- client/src/game/ui/reactive/view/premoveView.ts
- client/src/game/ui/reactive/view/replayView.ts
- client/src/game/ui/reactive/view/turn.ts
- client/src/game/ui/turn.ts
Fixes part of #1944 but not the draggability part. Have not tested extensively. I'll test alternating clues and bottom deck blind play right now. update: working well
> Refactor most of clue UI visibility code etc into views

- client/src/game/ui/reactive/view/statsView.ts
> Add number of finesses

- client/src/game/reducers/turnReducer.ts
> Fix panicky discard in final round

- server/src/characters.go
- server/src/command_action.go
Fixes #1933 
Tested that game JSON and I was able to play p5 and finish the game.
Testing now if normal games finish properly
> Fix contrarian endgame stuff

- client/src/game/reducers/replayReducer.test.ts
- client/src/game/reducers/replayReducer.ts
- client/src/game/reducers/stateReducer.ts
> hypo: Fix morphing cards into their real identities

- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/LayoutChild.ts
- client/src/game/ui/clues.ts
- client/src/game/ui/hypothetical.ts
- client/src/game/ui/noteCheckImpossibility.ts
> hypo: Fix playing a card during empathy

- client/src/game/ui/Elements.ts
- client/src/game/ui/controls/EnterHypoButton.ts
- client/src/game/ui/drawReplayArea.ts
- client/src/game/ui/reactive/StateObserver.ts
- client/src/game/ui/reactive/view/replayView.ts
> Move "Enter Hypothetical" button to the left during a game

- client/src/game/ui/HanabiCard.ts
> Fix note glitch in post-game hypo

- public/css/hanabi.css
> fix_pregame_css

- public/css/hanabi.css
Fixed annoying pregame scrollbar. Put chatboxes side by side if screen is wide enough
> Fix bug, put chat boxes side by side if possible

- data/characters.json
> Fix mood swings emoji

- client/src/game/reducers/noteIdentity.ts
Resolve #1801
`!b,g` means not blue and not green.
> Implement negative identity notes

- client/src/chat.ts
- client/src/game/ui/HanabiUI.ts
Fixes #2025 assuming I understand the issue correctly.
> Confirm `/suggest` less often

- client/src/game/reducers/getSoundType.ts
- client/src/game/rules/hyphenated.ts
- docs/CHAT_COMMANDS.md
- server/src/discord_commands_convention_questions.go
- server/src/views/main.tmpl
Pretty self explanatory, replace stale references to Reference.md and Beginner.md
> Update some stale URL's

- client/src/game/reducers/noteIdentity.test.ts
- client/src/game/reducers/noteIdentity.ts
- client/src/game/rules/abbreviation.ts
- client/src/game/types/constants.ts
First PR here.  I left the old code in and there is cruft. LMK if this needs changes. I can remove the old code.
#2028
#1801 
fixes #2102
> Added smart comma separated notes, fixed gray pink

- client/src/game/ui/HanabiCard.ts
> Appending notes uses bracket syntax

- client/src/chat.ts
- client/src/lobby/nav.ts
- client/src/lobby/pregame.ts
- server/src/views/main.tmpl
No issue. I just found it annoying that suggesting variants as a nonleader I would have to remember variant names exactly but there is already a perfectly good UI for that.
> Nonleaders can suggest variants using dropdown

- .cspell.json
- client/src/game/reducers/constants.ts
- client/src/game/reducers/noteIdentity.ts
- client/src/game/reducers/notesReducer.ts
- client/src/game/rules/abbreviation.ts
Also forbids suit abbreviation to be a reserved word.
> Notes parsing scans for reserved words

- client/src/game/reducers/noteIdentity.ts
- client/src/game/reducers/notesReducer.ts
- client/src/game/ui/HanabiCard.ts
Follows convention from chat w/ @Zamiell
> Improved appended notes

- .cspell.json
- client/src/chat.ts
- client/src/constants.ts
Start typing `Black`. Hit `up`.  Have it autocomplete everything you've said which started `Black...`
Hit `<enter>`.  Now that chat is pushed to the beginning of chat history so you don't have to scroll back to find it.
> Search through chat history

- client/src/chat.ts
- client/src/lobby/nav.ts
> Let players send commands to others via chat

- client/src/chat.ts
> proper 12pm hour timestamp

- client/src/lobby/pregame.ts
> Start Game Button disabled for 2" when join/leave

- client/src/game/reducers/constants.ts
- client/src/game/reducers/initialStates/initialState.ts
- client/src/game/reducers/notesReducer.ts
- client/src/game/rules/stats.ts
- client/src/game/types/CardNote.ts
- client/src/game/ui/HanabiCard.ts
> Added "clued" note

- server/src/views/history.tmpl
- server/src/views/profile.tmpl
Made the variant filter case insensitive. It also searches for variants containing the words typed in.
Total number of games changes according to the visible table rows
Closes #2084
> [server] Fix history template

- client/src/game/ui/notes.ts
> [client] allow < & > " in notes by using HTML entities

- client/src/game/ui/drawUI.ts
Fixes #2081 
Repositions "Your Turn" and background ellipse
> [client] Fix position of ellipses

- client/src/game/reducers/UIReducer.ts
- client/src/game/reducers/initialStates/initialState.ts
- client/src/game/reducers/replayReducer.test.ts
- client/src/game/reducers/stateReducer.test.ts
- client/src/game/reducers/stateReducer.ts
- client/src/game/types/State.ts
- client/src/game/types/UI.ts
- client/src/game/types/UICard.ts
- client/src/game/types/UIState.ts
- client/src/game/types/actions.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/HanabiCardMouse.ts
- client/src/game/ui/keyboard.ts
- client/test/loadGameJSON.ts
> fix shadow bug

- client/src/game/ui/drawCards.ts
> Show a pip for Start card

- client/src/game/reducers/initialStates/initialCardState.ts
- client/src/game/types/CardState.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/HanabiCardMouse.ts
- client/src/game/ui/notes.ts
> Show suits tooltips

- client/src/game/ui/HanabiCard.ts
> Use proper way to get abbreviation in the suit description

- client/src/game/ui/LayoutChild.ts
Since it seems there are five votes in favor and none against so far
> Implement #2172 disabling plays from rewind

- client/src/game/rules/stats.ts
- docs/CHAT_COMMANDS.md
- docs/FEATURES.md
- server/src/discord_commands_convention_questions.go
Stale links to old conventions repo are updated
> Fix dead links

- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/HanabiCardInit.ts
> Show start rank pip

- client/src/chat.ts
- client/src/game/ui/keyboard.ts
- client/src/game/ui/replay.ts
> Exit replay automatically when user uses keyboard controls to navigate to end

- client/src/game/reducers/ddaReducer.ts
- client/src/game/reducers/getSoundType.ts
- client/src/game/rules/card.ts
- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/noteCheckImpossibility.ts
See discussion thread in the issue #2222
> DDA fixup for #2222

- client/src/game/ui/replay.ts
> Fix shared replay controls

- client/src/game/ui/keyboard.ts
- client/src/game/ui/replay.ts
One of two alternative solutions for complaints about current replay auto-exit code.
> Exit replay automatically if already at end and moving forward

- client/src/game/ui/drawCards.ts
> In Synesthesia, do not recolor ranks on brown

- client/src/commands.ts
- client/src/lobby/createGame.ts
- client/src/lobby/pregame.ts
Tooltipster proper repositioning
Change options for non table hosts is disabled (for now)
> Change options for non host

- public/css/hanabi.css
> FIx mouse cursor for disabled nav links

- client/src/chat.ts
- public/css/hanabi.css
> Remove extra lines from pregame chat

- client/src/game/ui/Deck.ts
- client/src/lobby/history.ts
- client/src/lobby/pregame.ts
- client/src/types/Options.ts
- server/src/views/main.tmpl
> Clearer icon in history

- client/src/lobby/createGame.ts
- client/src/types/Options.ts
- public/css/hanabi.css
- server/src/command_replay_create.go
- server/src/command_table_update.go
- server/src/options.go
- Fixes options proposal by guest.
- Guest can also propose table name change
- UI indication if timer values in timed game are empty
> fix change, update table name

- client/src/game/ui/arrows.ts
- client/src/game/ui/drawUI.ts
Turn label was unclickable (as well as set turn prompt)
> fix right click (arrows) on game area

- client/src/game/ui/keyboard.ts
- client/src/game/ui/replay.ts
- client/src/game/ui/stats.ts
- client/src/modals.ts
- Set turn, play card and set modifier dialogs have the input value preselected
- Pressing ENTER on create game dialog submits the form
> preselection in dialogs, enter for submit in create game

- client/src/game/ui/keyboard.ts
- client/src/game/ui/replay.ts
- client/src/game/ui/stats.ts
- client/src/modals.ts
- public/css/hanabi.css
- server/src/views/main.tmpl
- restored lobby shortcuts for dialogs
- refactor
- narrower prompt dialogs
> Dialog fixes

- public/css/hanabi.css
- server/src/views/main.tmpl
> effort to make settings square-ish

- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/hypothetical.ts
> Morphed draggable, no error on hypo card play

- client/src/game/ui/HanabiCard.ts
- client/src/game/ui/HanabiCardClick.ts
- client/src/game/ui/LayoutChild.ts
- client/src/game/ui/timer.ts
- client/src/game/ui/uiInit.ts
- client/src/modals.ts
- public/css/hanabi.css
- server/src/views/main.tmpl
The last prompt replaced by a dialog
> Morph to modal

- client/src/globals.ts
- client/src/lobby/createGame.ts
- client/src/lobby/lobbyCommands.ts
- client/src/lobby/nav.ts
- client/src/lobby/pregame.ts
- client/src/lobby/tablesDraw.ts
- client/src/lobby/types/Game.ts
- client/src/lobby/types/Table.ts
- public/css/hanabi.css
- server/src/command.go
- server/src/command_table_create.go
- server/src/command_table_join.go
- server/src/command_table_start.go
- server/src/session_notify.go
- server/src/table.go
- server/src/table_notify.go
- server/src/views/main.tmpl
Merges #2055 (Maximum player option by @eskolnik) to master
> Merge #2055 and #2034 to master

- client/src/game/ui/notes.ts
> keypress ignores shift key

- .cspell.json
- client/src/chatCommands.ts
- server/src/command.go
- server/src/command_tags_delete_all.go
- server/src/models_game_tags.go
Used /tagsdeleteall to avoid mistyping confusion with /tagdelete
Closes #2152
> Implement /tagsdeleteall

- client/src/game/rules/variants/reversible.ts
> Fix critical case in up and downs

- client/src/game/rules/criticalNotification.test.ts
Doesn't change the test, it's just for humans looking at the test data / replay
> fix turn and title typo

- server/src/command_tags_delete_all.go
- server/src/models_game_tags.go
> A user can delete their tags with /tagsdeleteall

- client/src/game/ui/notes.ts
> Special keys removing the pipe are checked once

- client/src/game/ui/notes.ts
Allows users to write notes using quotes, less/greater than etc. (Nitrate)
> Create input and allow value encoding

- client/src/game/ui/clues.ts
> Prevent unknown cards from getting clues in hypo

- client/src/chatCommands.ts
Even /setvariant&nbsp;&nbsp;&nbsp;&nbsp;bLACK&nbsp;&nbsp;&nbsp;(&nbsp;&nbsp;6&nbsp;&nbsp;SuiTS ) works now 🥇
> Set variant like a boss

- client/src/game/ui/notes.ts
> Special keys removing the pipe are ignored the first time

- dev.sh
- hanab.code-workspace
- Added ./dev.sh to allow starting and stopping server and webpack with a single script
- Added workspace file definition for VSC
> Workspace folders dev script

- client/src/chatCommands.ts
> Better change variant

- data/suits.json
> Better VA colors in Very Ambiguous 6 suits

- server/src/command_table_restart.go
> Table restart sets previous t.MaxPlayers value

- .cspell.json
- client/src/chat.ts
- docs/CHAT_COMMANDS.md
- server/src/chat_command.go
- server/src/chat_general.go
> /levels command, include tagsdeleteall in docs

- server/src/views/main.tmpl
> Show number of online users in two tabs

- public/css/hanabi.css
> Show player status on mobile

- client/src/game/reducers/replayReducer.ts
- client/src/game/types/HypotheticalState.ts
- client/src/game/ui/reactive/view/cardsView.ts
> Hide starting player's hand in hypo (#2069)

- client/src/game/reducers/replayReducer.ts
- client/src/game/ui/HanabiCardMouse.ts
- client/src/game/ui/hypothetical.ts
- client/src/game/ui/reactive/view/cardsView.ts
- client/src/game/ui/reactive/view/hypotheticalView.ts
> Show empathy on hidden cards during hypo

- client/src/game/ui/HanabiCardMouse.ts
> Hypo on keldon

- public/css/hanabi.css
- server/src/views/profile.tmpl
> Fewer filters with less width

- .cspell.json
- public/css/hanabi.css
- server/src/api_games.go
- server/src/api_misc.go
- server/src/api_variants.go
- server/src/http.go
- server/src/http_history.go
- server/src/http_misc.go
- server/src/http_seed.go
- server/src/http_variant.go
- server/src/models_games.go
- server/src/variants.go
- server/src/views/players_history.tmpl
- server/src/views/variant.tmpl
Needs build_client
Has new css
Closes #2203
Relates to #2368
> Ajax for /history, /variant, /seed

- public/css/hanabi.css
- server/src/views/players_history.tmpl
- server/src/views/variant.tmpl
> Spinner during ajax calls

- client/src/lobby/createGame.ts
Reported by @mmelwen and others
Relates to #2279
> Fixed delegated event handler

- client/src/lobby/createGame.ts
> Close new game modal before sending the command

- data/suits.json
- data/variants.json
- scripts/python/create_variants_json.py
> Rename Ruby to Orange

- client/src/game/reducers/gameStateReducer.ts
- client/src/game/rules/text.ts
- client/src/game/types/GameMetadata.ts
- client/src/game/types/actions.ts
- client/test/loadGameJSON.ts
- server/src/actions.go
- server/src/command.go
- server/src/command_action.go
- server/src/command_table_vote_for_termination.go
- server/src/table.go
> Vtk messages

- server/src/restart.go
> Shutdown reported to website-dev channel

- server/src/discord_commands_special.go
> /issue [id] shows an old issue

- client/src/game/rules/abbreviation.ts
> Skip over d/a/r/k

- client/src/game/ui/drawUI.ts
> Fix for num_games < 1000

- server/src/discord_commands_special.go
> /issue [int] works for all

- server/src/restart.go
> Shows uptime before shutting down

- .github/workflows/ci.yml
Resources:
- https://github.com/marketplace/actions/changed-files
- https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
Not sure how the discord notifications will behave
> Run actions based on what's changed

- .github/workflows/ci.yml
> Separate client/server actions

- client/src/game/types/GameMetadata.ts
> Return "The players" in replay

- admin/sendWarningAll.sh
- server/src/http_localhost.go
- server/src/http_localhost_send_warning.go
> /sendWarningAll local command

- .gitignore
- packages/client/src/game/ui/drawCards.ts
> Draw special 1s and 5s according to their special rank property

- Dockerfile
I don't know much about node/go, but that looks right and got it to work on my dev.
> Fixing Dockerfile after latest refactoring

- packages/client/src/game/ui/drawCards.ts
- packages/client/src/game/ui/drawStylizedRank.ts
> Draw deceptive 1s, 5s

- packages/client/src/chatCommands.test.ts
- packages/client/src/chatCommands.ts
- packages/client/src/game/types/JSONGame.ts
- packages/client/src/lobby/createReplayJSON.ts
- packages/data/src/hypoPlayerNames.ts
- packages/data/src/index.ts
> Hypo to clipboard

- packages/client/src/game/ui/reactive/view/replayView.ts
> Check for segment number first in replay

- server/src/api_games.go
- server/src/api_misc.go
- server/src/api_variants.go
> API disallowed for banned IPs

- server/src/command_replay_create.go
- server/src/command_table_create.go
- server/src/command_table_update.go
- server/src/misc.go
> Seed names

- server/src/api_games.go
- server/src/api_variants.go
> API returns empty instead off null

- packages/client/src/modals.ts
> Replace color strings

- server/src/chat.go
- server/src/command_chat.go
- server/src/discord.go
> Replace Regex, add searching for roles, everywhere

- packages/client/src/lobby/createReplayJSON.ts
> SLR, fix regex, search start, search color clues not suits

- packages/client/src/game/ui/HanabiCardMouse.ts
> Make checks

- packages/client/src/game/ui/HanabiCardClick.ts
- packages/client/src/game/ui/LayoutChild.ts
- packages/client/src/game/ui/drawCards.ts
- packages/client/src/modals.ts
- server/src/views/main.tmpl
* Fix clicking
* Require only 1 click instead of 2
* Select the current card by default
> Change morphing modal:

- package-lock.json
- package.json
rel #2435 
`npm run variants` from project root
> Create script for variants in ts

- docs/FEATURES.md
> Update emojis link

- packages/client/src/lobby/login.ts
- public/css/hanabi.css
- server/src/http_login.go
- server/src/models_users.go
- server/src/views/main.tmpl
It's the same commit, I just undid by hand in main.tmpl what an extension I didn't choose to install and force into the codebase did.
> Change password

- docs/VARIANTS.md
- misc/variants.txt
- packages/client/src/game/rules/clues.ts
- packages/data/src/json/variants.json
- packages/data/src/types/Variant.ts
- packages/data/src/variantsInit.ts
- scripts/python/create_variants_json.py
- scripts/typescript/create_variants_json.ts
- server/src/variant.go
- server/src/variants.go
Closes #2299 
Props to Romain672 for the new variant
> Those cards are odd

- packages/client/src/game/rules/stats.ts
Thanks to @N1trate for catching this
> Restore wrongly removed hyphen

- server/src/discord_command.go
- server/src/discord_commands_special.go
- server/src/github.go
- server/src/misc.go
Closes #1968 
Usage: `/mem` or `/memory` from Discord
Private use only
Works but 🔥untested Discord part
> Implement /mem, /memory

- packages/client/src/game/ui/reactive/view/statsView.ts
- packages/client/src/lobby/pregame.ts
> Fix all or nothing

- packages/client/src/lobby/usersDraw.ts
- public/css/hanabi.css
> Align non-h users in Online Users box

- packages/client/src/game/rules/clues.ts
- server/src/variants.go
> Special suits take precedence in clues before O&E

- .cspell.json
- .env_docker_template
- .env_template
- docs/CHAT_COMMANDS.md
- packages/client/src/chat.ts
- server/src/chat_command.go
- server/src/chat_info.go
- server/src/command_chat.go
- server/src/discord.go
- server/src/discord_command.go
- server/src/discord_commands_duplicated.go
🔥🔥 **Attention** 🔥🔥
The following modifications required for this to work
Add the following lines:
```
DISCORD_PING_CREW_ROLE_NAME="Ping Crew"
DISCORD_TRUSTED_TEACHER_ROLE_NAME="Trusted Teacher"
```
The role of `Hanab-Bot` has to have higher hierarchy from `Ping Crew`
(Server settings -> Roles -> move Hanab-bot higher)
> /ping, /here, /teachme, /subscribe, /unsubscribe

- server/src/views/players_history.tmpl
Closes #2577 
Need to run db query detailed in the issue, this PR fixes JS errors only.
> Prevent errors in template

- packages/client/src/lobby/url.ts
> Fix replay link

- docs/CHAT_COMMANDS.md
- docs/COMMUNITY_GUIDELINES.md
- docs/FEATURES.md
- docs/RULES.md
- docs/VARIANTS.md
- Run prettier on all .md files
- Sort logical groups of commands
- Corrections, additions
> Fix MD files

- packages/client/src/game/ui/HanabiCardClick.ts
> Allow arrows in solo replay

- packages/client/src/game/ui/controls/PlayerButton.ts
- packages/client/src/game/ui/drawUI.ts
> Make cluing UI more obvious

- LICENSE
- package-lock.json
- package.json
- packages/card-images/package.json
- packages/client/package.json
- packages/data/package.json
- packages/server-old/package.json
Partially revert bddce95c97a427ff079ed7064362a2edf643dd6c
See #2625
> Set license back from AGPL to GPL

- packages/client/src/game/types/Pips.ts
- packages/client/src/game/ui/HanabiCard.ts
- packages/client/src/game/ui/HanabiCardInit.ts
- packages/client/src/game/ui/drawPip.ts
- packages/client/src/game/ui/reactive/view/cardsView.ts
> Positive color clues

- server/src/command_note.go
- server/src/command_table_spectate.go
- server/src/command_table_unattend.go
- server/src/game_end.go
- server/src/session_notify.go
- server/src/spectator.go
- server/src/table_notify.go
> Fix panic on adding note to a game with pre-game spectators

- packages/client/src/game/types/Pips.ts
- packages/client/src/game/ui/HanabiCard.ts
- packages/client/src/game/ui/HanabiCardInit.ts
- packages/client/src/game/ui/drawPip.ts
- packages/client/src/game/ui/reactive/view/cardsView.ts
> Positive color clues (fixed)

- server/src/command_table_unattend.go
> Fix bug preventing pre-game spectators from leaving the pre-game

- packages/client/src/game/reducers/gameStateReducer.test.ts
- packages/client/src/game/reducers/gameStateReducer.ts
- packages/client/src/game/reducers/replayReducer.ts
- packages/client/src/game/reducers/stateReducer.ts
- packages/client/src/game/rules/text.ts
- packages/client/test/loadGameJSON.ts
Adds "[Hypo]" in front of hypo actions in the replay, closes #2643
> Resolves #2643

- packages/client/src/game/ui/HanabiCard.ts
- packages/client/src/game/ui/HanabiCardClick.ts
`#13 #12 #11 note` => `#13 note`
> Fixed turn count note

- packages/client/src/chat.ts
- packages/client/src/chatCommands.ts
- packages/client/src/game/ui/HanabiUI.ts
- packages/client/src/game/ui/gameCommands.ts
- server/src/command.go
- server/src/command_table_suggest.go
- server/src/session_notify.go
- server/src/table_notify.go
Adding /suggest to gameCommands
to be dispached to server
instead of parsed out in the chat.ts
> Adding /suggest to gameCommands

- packages/data/update_variant_files.sh
> Fix path in update_variant_files.sh

- packages/client/src/game/reducers/notesReducer.ts
- packages/client/src/game/types/SpectatorNote.ts
- packages/client/src/game/types/actions.ts
- packages/client/src/game/ui/gameCommands.ts
- packages/client/src/game/ui/notes.ts
- public/css/hanabi.css
- server/src/chat_pregame.go
- server/src/command_chat.go
- server/src/command_chat_read.go
- server/src/command_chat_typing.go
- server/src/command_get_game_info_1.go
- server/src/command_get_game_info_2.go
- server/src/command_note.go
- server/src/command_replay_action.go
- server/src/command_table_restart.go
- server/src/command_table_spectate.go
- server/src/command_table_start.go
- server/src/command_table_unattend.go
- server/src/game_end.go
- server/src/http_localhost_clear_empty_tables.go
- server/src/print.go
- server/src/session_notify.go
- server/src/spectator.go
- server/src/table.go
- server/src/table_notify.go
- server/src/tables.go
- server/src/websocket_disconnect.go
Fixing the previous bugs and made some cleaner code.
> Savespecnotes

- server/src/models_games.go
- server/src/websocket_connect.go
Made the friendsHistoryID little sharper and put connecting Messages in a separate go routine to not hinder other connecting users if one is slow
> Put connect messages in a go routine

- server/src/command_note.go
Removes html escpaing in the server, it's a job for the client
> Removes Html escaping on the server

- packages/client/src/game/ui/HanabiCard.ts
- packages/client/src/game/ui/reactive/view/cardsView.ts
Subscripbes to chenges of isKnownTrashFromEmpathy to update card status
> Update trash icon when possible

- packages/client/src/game/reducers/cardDeductionReducer.ts
If we know we have mophed cards that create an impossible deck, this will break empathy on all cards. We can remove them to make it work better.
> Fixes empathy in hypos with morphed cards

- packages/client/src/game/ui/HanabiCard.ts
Return early from setStatus if we are in RealTimeMode
> Don't display status images in realTimeMode

- packages/client/src/game/reducers/cardDeductionReducer.ts
- packages/client/src/game/reducers/noteIdentity.ts
- packages/client/src/game/reducers/replayReducer.ts
- packages/client/src/game/types/CardIdentityType.ts
- packages/client/src/lobby/createReplayJSON.ts
- packages/client/src/modals.ts
- public/css/hanabi.css
- server/src/views/main.tmpl
A few updates involving morphing
- Morph to blank or unmorph
- Fade out invalid cards in morph modal
- Use morphed cards when deducing
- Copy morphed cards with /copy
- Use escape to close the morph modal
> Morph updates

- packages/client/src/lobby/createReplayJSON.ts
> Copy bombs as well

- packages/client/src/game/ui/HanabiCardMouse.ts
> Fixes drag problems in hypo

- packages/client/src/game/ui/arrows.ts
- packages/client/src/game/ui/clues.ts
> Correctly show reclue arrow in clue preview

- packages/client/src/chatCommands.ts
> Added /untag

- packages/client/src/game/reducers/gameStateReducer.test.ts
- packages/client/src/game/reducers/gameStateReducer.ts
- packages/client/src/game/reducers/initialStates/initialState.ts
- packages/client/src/game/reducers/replayReducer.ts
- packages/client/src/game/reducers/stateReducer.ts
- packages/client/src/game/reducers/statsReducer.ts
- packages/client/src/game/rules/stats.ts
- packages/client/src/game/rules/text.ts
- packages/client/src/game/types/InitData.ts
- packages/client/src/game/types/State.ts
- packages/client/src/game/types/actions.ts
- packages/client/src/game/ui/PlayStack.ts
- packages/client/src/game/ui/drawUI.ts
- packages/client/src/game/ui/gameCommands.ts
- packages/client/src/game/ui/reactive/view/gameInfoView.ts
- packages/client/test/loadGameJSON.ts
- packages/client/test/testActions.ts
- server/src/command_get_game_info_1.go
> Making shadowing in ThrowItInAHole work

- packages/client/src/game/reducers/gameStateReducer.test.ts
- packages/client/src/game/reducers/gameStateReducer.ts
- packages/client/src/game/reducers/replayReducer.test.ts
- packages/client/src/game/reducers/replayReducer.ts
- packages/client/src/game/reducers/stateReducer.ts
- packages/client/src/game/ui/drawUI.ts
- packages/client/test/loadGameJSON.ts
Needed to know if the game was finished, to be able to "not throw it in a hole" in replay hypos
> Fixes ThrowItInAHole Hypos in replay and displays "Plays" label

- packages/client/src/lobby/tablesDraw.ts
- public/css/hanabi.css
> Join a game as hydra head from lobby

- packages/client/src/game/types/Spectator.ts
- packages/client/src/game/ui/gameCommands.ts
- packages/client/src/game/ui/reactive/view/spectatorsView.ts
- packages/client/src/lobby/lobbyCommands.ts
- packages/client/src/lobby/nav.ts
- packages/client/src/lobby/pregame.ts
- packages/client/src/lobby/tablesDraw.ts
- packages/client/src/lobby/types/Table.ts
- packages/client/src/lobby/types/WelcomeData.ts
- packages/client/src/lobby/url.ts
- public/css/hanabi.css
- server/src/command_get_game_info_1.go
- server/src/command_table_spectate.go
- server/src/game_end.go
- server/src/http.go
- server/src/session_notify.go
- server/src/spectator.go
- server/src/tables.go
- server/src/websocket_connect.go
- server/src/websocket_disconnect.go
- Adding shadowing in preplay
- Adding shadowing after reconnect
- Adding shadowing in the url
> Shadow Player in preplay and after reconnect

- packages/client/src/lobby/pregame.ts
> Removed strikeouts from total variants

- packages/client/src/game/ui/controls/TimerDisplay.ts
- packages/client/src/game/ui/timer.ts
> Red timer on player running out of time

- packages/client/src/game/ui/LayoutChild.ts
> Disable unplayable warnings in hypothetical

- server/src/command_get_game_info_1.go
> Don't change outPlayerIndex if we are a player

- server/src/views/history.tmpl
- server/src/views/missing-scores.tmpl
- server/src/views/scores.tmpl
This changes them to all spaces
> Server *.tmpl has some mixed tabs/spaces

- server/src/command_table_vote_for_termination.go
- server/src/table.go
> Require 2 votes to kill a 2 player game

- packages/client/src/game/ui/clues.ts
> Disable give clue button after click

- packages/client/src/game/ui/drawUI.ts
Left click the skull to vtk. Right click to terminate immediately
> Terminate with right click

- server/src/game_end.go
Creates the replay name:
My random name (Game #1234)
Closes #2781
> Keep the name of the shared replay

- packages/client/src/game/ui/keyboard.ts
> Toggle empathy properly in hypo with space bar

- packages/client/src/game/ui/HanabiCard.ts
> Display morphed card on empathy

- packages/client/src/game/reducers/replayReducer.ts
- packages/client/src/game/types/CardIdentity.ts
- packages/client/src/game/types/actions.ts
- packages/client/src/game/ui/HanabiCard.ts
- packages/client/src/lobby/createReplayJSON.ts
Fixing some bugs related to mophed cards and empathy
> Fixing morph card identity

- packages/client/src/game/ui/HanabiCard.ts
- packages/client/src/game/ui/drawCards.ts
> Deceptive brown cards should't have special rank

- packages/client/src/game/reducers/cardsReducer.ts
- packages/client/src/game/reducers/gameStateReducer.ts
- packages/client/src/game/reducers/replayReducer.ts
- packages/client/src/game/types/actions.ts
- packages/client/src/game/ui/clues.ts
> No negative information to hidden cards

- packages/client/src/game/ui/Deck.ts
- packages/client/src/lobby/pregame.ts
- packages/client/src/lobby/tablesDraw.ts
- packages/client/src/lobby/types/Table.ts
- packages/client/src/types/OptionIcons.ts
- public/css/hanabi.css
- server/src/session_notify.go
- server/src/views/main.tmpl
> Added options to lobby table and game name in-game

- public/css/hanabi.css
- server/src/views/main.tmpl
> Aligns text and moves magnifying glass into search

- cspell.json
- public/css/hanabi.css
- public/css/lib/alpha.css
> Fixing the selector arrow in create new game

- server/src/command_table_join.go
> Delete spectating relation if joining as player

- public/css/hanabi.css
Removed pointer on tooltips and changed image origin to center of image on custom cursors
Closes #2807
> Change custom cursor image origin to center

- packages/client/src/game/ui/HanabiCard.ts
Show card backs in duck (and cow&pig)
> Closes #1798

- docs/VARIANTS.md
Closes #2713 unless someone invents a name worth the extra complexity
> doc: write out dual-color suits

- docs/VARIANTS.md
yank out the dual-color formatting changes that got mixed into #2814
> Formatting changes for just dual-color

- packages/data/src/json/suits.json
Closes #2738, happy to take other proposals for hex codes
> Somewhat better colors for matryoshka

- server/src/api_variants.go
- server/src/models_games.go
- server/src/views/variant.tmpl
> Add seed link on variant list page

- docs/CHAT_COMMANDS.md
- packages/data/src/json/chatReplyCommands.json
- Add /github link to the git repository
- Add /variants link to the descriptions of variants
- Remove /ptt command (it led to a broken link)
> Edit simple chat commands

- server/src/views/missing-scores.tmpl
Change the color in `/m` accordingly.
> Hard variant is >= 1.33 now

- server/src/models_chat_log.go
> Make DB query for chat log deterministic by adding secondary sorting key

- packages/client/src/game/rules/playStacks.ts
- packages/client/src/game/rules/variants/reversible.ts
Fixes #2856. I hope this is correct now, could use some more testing for edge cases, but worked fine so far.
> Fix empathy up or down

- packages/data/src/json/suits.json
see https://discord.com/channels/140016142600241152/333680903748321282/1140489080879194213
> Fix RGB mix

- docs/chat-commands.md
- packages/client/src/chatCommands.ts
- server/src/chat_command.go
> Add /terminate command

- docs/chat-commands.md
- docs/features.md
> Document linked account feature

- server/src/main.go
We need to adjust this path in the server after the recent refactors.
> This has been refactored from @data to @game

- packages/client/src/game/ui/HanabiCard.ts
- packages/game/src/reducers/statsReducer.ts
As I was trying to tackle https://github.com/Hanabi-Live/hanabi-live/issues/2875, I thought this low-hanging fruit would be a good way to start.  Does this commit look okay to you?
EDIT: This is the error that should no longer be reachable: https://github.com/Hanabi-Live/hanabi-live/blob/main/packages/client/src/game/ui/reactive/getSoundType.ts#L208
We're now computing the number of blind "plays" successfully. Previously, it was set to 0 for TIIAH bombs.
> [Throw it in a Hole] Fix sound & stack bugs

- server/src/command_table_join.go
- server/src/command_table_reattend.go
- server/src/command_table_spectate.go
> Fix: update spectators list when reattending

- packages/client/esbuild_dev.sh
- packages/client/src/chat.ts
- packages/server/src/templates/main.eta
- public/css/hanabi.css
- server/src/views/main.tmpl
Adds an emoji button to the right end of the chat input that opens modal for selecting emotes and emojies.
> Feat: add emote/emoji picker

- server/src/chat_pregame.go
Implements the idea from #2970
> Feat: add apply changes button for find-variant command
